services:
  - type: web
    name: vehicle_app_main
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: |
      flask db upgrade && gunicorn run:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://vehicle_db_590a_user:GaI49vu5tRz4fhVeevaUbfSpx6Ce3GJD@dpg-d063nuali9vc73dvmm00-a.singapore-postgres.render.com/vehicle_db_590a
      - key: ENVIRONMENT
        value: prod
      - key: GUNICORN_CMD_ARGS
        value: "--timeout 300 --graceful-timeout 60 --workers 1"
