"""add Estimation model

Revision ID: 3f58a4e41f42
Revises: f798a820db70
Create Date: 2025-04-24 17:45:17.138849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f58a4e41f42'
down_revision = 'f798a820db70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estimations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maker', sa.String(), nullable=True),
    sa.Column('car_name', sa.String(), nullable=True),
    sa.Column('model_code', sa.String(), nullable=True),
    sa.Column('estimate_price', sa.Integer(), nullable=True),
    sa.Column('estimated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estimations')
    # ### end Alembic commands ###
