"""add model_code_id to Vehicle

Revision ID: 5b78c84d4515
Revises: 61ad66ab21fa
Create Date: 2025-10-16 23:03:02.705456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b78c84d4515'
down_revision = '61ad66ab21fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('estimations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_code_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'model_codes', ['model_code_id'], ['id'])

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_code_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'model_codes', ['model_code_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('model_code_id')

    with op.batch_alter_table('estimations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('model_code_id')

    op.drop_table('model_codes')
    # ### end Alembic commands ###
