"""Add 5 fields to Estimation

Revision ID: b39d2cfd4a4e
Revises: 3f58a4e41f42
Create Date: 2025-04-29 07:02:20.977152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b39d2cfd4a4e'
down_revision = '3f58a4e41f42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estimations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sale_price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('buyer', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sold_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('note', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estimations', schema=None) as batch_op:
        batch_op.drop_column('note')
        batch_op.drop_column('sold_at')
        batch_op.drop_column('buyer')
        batch_op.drop_column('sale_price')
        batch_op.drop_column('owner')

    # ### end Alembic commands ###
