"""initial

Revision ID: f798a820db70
Revises: 
Create Date: 2025-04-22 07:39:30.106267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f798a820db70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intake_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('pickup_date', sa.Date(), nullable=True),
    sa.Column('client', sa.String(), nullable=True),
    sa.Column('car_name', sa.String(), nullable=True),
    sa.Column('model_code', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('vin', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('estimate_price', sa.Integer(), nullable=True),
    sa.Column('internal_code', sa.String(), nullable=True),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scraped_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('manufacturer_name', sa.String(), nullable=True),
    sa.Column('model_spec', sa.String(), nullable=True),
    sa.Column('retrieved_date', sa.Date(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scraped_info')
    op.drop_table('vehicles')
    op.drop_table('manufacturers')
    # ### end Alembic commands ###
